### Load Library

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#################################
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier, BaggingClassifier
###################################
from sklearn.datasets import load_digits

### Load Data

In [2]:
data = load_digits()

In [3]:
# Define Data
x = data.data
y = data.target

In [5]:
print("X shape : {}".format(x.shape))
print("Y shape : {}".format(y.shape))

X shape : (1797, 64)
Y shape : (1797,)


### Preprocessing

In [8]:
# Scale Data
scale = StandardScaler()
# Fit Data
x = scale.fit_transform(x)

In [12]:
# Train Test Split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42, test_size=0.33)

### Model

In [15]:
rfc = RandomForestClassifier(max_depth=4)

In [16]:
rfc.fit(x_train, y_train)

C:\Users\amras\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=4, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [17]:
# predict data
y_pred = rfc.predict(x_test)

In [18]:
## Confusion Matrix And Classification Report
print("Confusion Matrix :\n")
print(confusion_matrix(y_test, y_pred))
print()
print("Classification Report :\n")
print(classification_report(y_test, y_pred))

Confusion Matrix :

[[54  0  0  0  1  0  0  0  0  0]
 [ 0 42  5  0  4  0  2  0  0  2]
 [ 0  0 48  3  0  0  0  0  1  0]
 [ 1  2  1 47  0  0  0  0  4  1]
 [ 1  0  0  0 60  0  2  1  0  0]
 [ 0  0  0  0  2 59  1  0  0 11]
 [ 1  0  0  0  1  0 55  0  0  0]
 [ 0  0  0  0  3  1  0 58  0  0]
 [ 1  4  5  3  1  0  0  4 34  0]
 [ 1  0  1  3  1  2  0  4  1 55]]

Classification Report :

              precision    recall  f1-score   support

           0       0.92      0.98      0.95        55
           1       0.88      0.76      0.82        55
           2       0.80      0.92      0.86        52
           3       0.84      0.84      0.84        56
           4       0.82      0.94      0.88        64
           5       0.95      0.81      0.87        73
           6       0.92      0.96      0.94        57
           7       0.87      0.94      0.90        62
           8       0.85      0.65      0.74        52
           9       0.80      0.81      0.80        68

    accuracy               

### Bagging And Boosting

In [19]:
# Define Bagging
bg = BaggingClassifier(rfc, n_estimators=20)

In [20]:
bg.fit(x_train, y_train)

BaggingClassifier(base_estimator=RandomForestClassifier(bootstrap=True,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=4,
                                                        max_features='auto',
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        n_estimators=10,
                                                        n_jobs=None,
           

In [21]:
# Predict Data
bg_pred = bg.predict(x_test)

In [24]:
## Confusion Matrix And Classification Report
print("Confusion Matrix :\n")
print(confusion_matrix(y_test, bg_pred))
print()
print("Classification Report :\n")
print(classification_report(y_test, bg_pred))
print("""

     Accuracy in  RandomForest Classifier => 0.83 
     Accuracy in  Bagging      Classifier => 0.93


""")

Confusion Matrix :

[[54  0  0  0  1  0  0  0  0  0]
 [ 0 48  4  0  0  1  0  0  0  2]
 [ 0  0 50  1  0  0  0  0  1  0]
 [ 0  0  0 53  0  0  0  0  3  0]
 [ 0  0  0  0 60  0  0  4  0  0]
 [ 0  0  0  0  1 64  1  0  0  7]
 [ 0  0  0  0  1  0 56  0  0  0]
 [ 0  0  0  0  0  1  0 61  0  0]
 [ 0  3  1  0  0  1  0  1 45  1]
 [ 0  0  0  2  0  1  0  4  0 61]]

Classification Report :

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        55
           1       0.94      0.87      0.91        55
           2       0.91      0.96      0.93        52
           3       0.95      0.95      0.95        56
           4       0.95      0.94      0.94        64
           5       0.94      0.88      0.91        73
           6       0.98      0.98      0.98        57
           7       0.87      0.98      0.92        62
           8       0.92      0.87      0.89        52
           9       0.86      0.90      0.88        68

    accuracy               

### Boosting

In [25]:
# Define Boosting
bs = AdaBoostClassifier(bg, n_estimators=50)

In [26]:
# Fit Data
bs.fit(x_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=BaggingClassifier(base_estimator=RandomForestClassifier(bootstrap=True,
                                                                                          class_weight=None,
                                                                                          criterion='gini',
                                                                                          max_depth=4,
                                                                                          max_features='auto',
                                                                                          max_leaf_nodes=None,
                                                                                          min_impurity_decrease=0.0,
                                                                                          min_impurity_split=None,
                                                                                

In [27]:
# predict data
bs_pred = bs.predict(x_test)

In [29]:
## Confusion Matrix And Classification Report
print("Confusion Matrix :\n")
print(confusion_matrix(y_test, bs_pred))
print()
print("Classification Report :\n")
print(classification_report(y_test, bs_pred))
print("""

     Accuracy in  RandomForest Classifier => 0.83 
     Accuracy in  Bagging Classifier      => 0.93
     Accuracy in  AdaBoostClassifier      => 0.97


""")

Confusion Matrix :

[[55  0  0  0  0  0  0  0  0  0]
 [ 0 54  0  0  0  0  0  0  0  1]
 [ 0  0 49  0  0  0  0  0  3  0]
 [ 0  0  0 51  0  1  0  0  4  0]
 [ 0  0  0  0 63  0  1  0  0  0]
 [ 0  0  0  0  1 69  0  0  1  2]
 [ 0  0  0  0  0  1 56  0  0  0]
 [ 0  0  0  0  0  0  0 61  0  1]
 [ 0  0  0  0  0  1  0  0 51  0]
 [ 0  0  0  0  0  0  0  0  3 65]]

Classification Report :

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        55
           1       1.00      0.98      0.99        55
           2       1.00      0.94      0.97        52
           3       1.00      0.91      0.95        56
           4       0.98      0.98      0.98        64
           5       0.96      0.95      0.95        73
           6       0.98      0.98      0.98        57
           7       1.00      0.98      0.99        62
           8       0.82      0.98      0.89        52
           9       0.94      0.96      0.95        68

    accuracy               